$schema: "http://json-schema.org/2020-12/schema#"

description: snakemake configuration file

type: object

properties:
  dataset:
    description: Variant dataset directory in data/raw/variants
    type: string
    pattern: "^[^/]+$"
  description:
    description: >-
      Description of analysis.
    type: string
  ref:
    description: Reference sequence file
    type: string
    pattern: .+\.(fa|fasta)$
  samples:
    description: >-
      Sample definition file.
    type: string
    pattern: .+\.(tsv|csv)$
  populations:
    description: >-
      Population definition file.
    type: string
    pattern: .+\.(tsv|csv)$
  chromosomes:
    description: >-
      List of chromosomes to analyse.
    type: array
    items:
      type: string
  subset:
    type: object
    properties:
      include:
        patternProperties:
          '[a-zA-Z0-9_]+':
            description: >-
              Keys in sample data frame for selecting subsets of
              samples. All samples are included if left empty.
            type: array
            items:
              type: string
      exclude:
        patternProperties:
          '[a-zA-Z0-9_]+':
            description: >-
              Keys in sample data frame for excluding subsets of
              samples.
            type: array
            items:
              type: string
  derive_aa:
    type: object
    default: {}
    properties:
      method:
        type: string
        default: 'vote'
        enum: ['vote'] ## Add methods suggested on tsinfer list here
      options:
        type: object
        default: {}
      outgroups:
        type: array
        default: []
        items:
          type: string
          uniqueItems: true
    additionalProperties: false



# entries that have to be in the config file for successful validation
required:
  - samples
  - chromosomes
  - ref
  - dataset
  - analysis
