$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

properties:
  description:
    description: >-
      Description of analysis.
    type: string
  ref:
    description: reference sequence
    type: string
    pattern: .+\.(fa|fasta)$
  samples:
    description: >-
      sample definition file
    type: string
    pattern: .+\.(tsv|csv)$
  chromosomes:
    description: >-
      List of chromosomes to analyse. Can be set in analysis section.
    type: array
    items:
      type: string
  derive_aa:
    type: object
    default: {}
    properties:
      method:
        type: string
        default: 'vote'
        enum: ['vote'] ## Add methods suggested on tsinfer list here
      options:
        type: object
        default: {}
      outgroups:
        type: array
        default: []
        items:
          type: string
          uniqueItems: true
    additionalProperties: false



# entries that have to be in the config file for successful validation
required:
  - samples
  - chromosomes
  - ref
