include: "rules/common.smk"
include: "rules/tsinfer.smk"
include: "rules/ancestral.smk"

report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"


rule all:
    input: unpack(all)

rule all_tsinfer:
    input: all_tsinfer
