channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools
  - bokeh
  - cyvcf2
  - matplotlib
  - pandas
  - pyfaidx
  - pygments
  - python>=3.7
  - scipy>=1.9.3
  - snakemake-minimal>=7.0
  - tqdm
  - tsinfer
  - zarr=2.10.0
