channels:
  - conda-forge
  - bioconda
  - default
dependencies:
  - bcftools
  - bokeh=2.4.3
  - cyvcf2
  - matplotlib
  - pandas
  - pyfaidx
  - pygments
  - python>=3.7,<3.12
  - scipy>=1.9.3
  - snakemake-minimal>=7.0
  - tqdm
  - tsinfer
  - zarr
