include: "rules/common.smk"
include: "rules/tsinfer.smk"
include: "rules/relate.smk"


if "derive_aa" in config:

    include: "rules/ancestral.smk"


report: "report/workflow.rst"


rule all:
    input:
        unpack(all),


rule all_tsinfer:
    input:
        all_tsinfer,
