ref: "resources/ref_tsk_CHB_0.fa"
samples: "resources/samples.tsv"
populations: "resources/populations.tsv"
derive_aa:
  method: 'vote'
  outgroups:
    - tsk_chimp
    - tsk_gorilla
    - tsk_orangutan
  options:
    n: 4

chromosomes:
  - '1'

tsinfer/test:
  description: >-
    Test run on chromosome 1, Out of Africa dataset
  dataset: ooa
  fmt: ooa_{chrom}_PASS
  subset:
    include:
      population: ["CEU", "CHB", "YRI"]
