name: Tests

on:
  push:
  pull_request:
    branches_ignore: []

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: src/tswf
        snakefile: src/tswf/workflow/Snakefile
        args: "--lint"
        stagein: >-
          python -m pip install .

  Testing:
    runs-on: ubuntu-latest
    needs: Linting
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: [3.9]
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Create conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,bioconda,default
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yaml
    - name: Install repo
      run: python -m pip install .
    - name: Test workflow (local test data)
      run: tswf smk run --test
    - name: Test report
      run: tswf smk run --test --report report.zip
