name: Tests

on:
  push:
  pull_request:
    branches_ignore: []

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: src/tswf
        snakefile: src/tswf/workflow/Snakefile
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs: Linting
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Install snakemake environments
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: src/tswf/tests
        snakefile: src/tswf/workflow/Snakefile
        args: "-j 2 --use-conda --conda-create-envs-only"
    - name: Test workflow (local test data)
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: src/tswf/tests
        snakefile: src/tswf/workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs cache"
    - name: Test report
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: src/tswf/tests
        snakefile: src/tswf/workflow/Snakefile
        args: "--report report.zip"
