name: Tests

on:
  push:
  pull_request:
    branches_ignore: []

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies to lmdb
        run: sudo apt-get install libffi-dev build-essential
      - name: Lint workflow
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: src/tswf/tests
          snakefile: src/tswf/workflow/Snakefile
          args: "--lint"
          stagein: "mamba env update --name=base --file=environment.yml; mamba install -c conda-forge -c bioconda -c default ruamel.yaml; python -m pip install --no-deps ."

  Testing:
    runs-on: ubuntu-latest
    needs: Linting
    timeout-minutes: 30
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Create conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          environment-file: conda-linux-64.lock
          use-only-tar-bz2: true
      - name: Install test dependencies
        run: conda install -c conda-forge pytest pip
      - name: Install repo
        run: python -m pip install .
      - name: Test workflow (local test data)
        run: tswf smk run --test
      - name: Test report
        run: tswf smk run --test --report report.zip
      - name: Test code
        run: pytest -v -s
